Added Hex VTK output
jlchan/StartUpDG.jl pull request #144
Opened 2023-06-15 16:17 UTC by jmark

Title says it all. :)

2023-06-15 17:32 UTC, jlchan requested changes
Thanks! I appreciate you adding this. Just have a few minor suggestions.

2023-06-15 17:32 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +points of a `VTK_LAGRANGE_TRIANGLE`
Thanks for catching this!

2023-06-15 17:32 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    num_verts_on_edge = order - 1
`verts` here refers to nodes on a given edge, right? I noticed the other routines also use this terminology. Would you mind doing a search-and-replace for the other instances too?
```suggestion
    num_nodes_on_edge = order - 1
```

2023-06-15 17:32 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    )
Is this VTK ordering? If so, can you add a comment noting that?

2023-06-15 17:32 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    )
Is this VTK ordering? If so, can you add a comment?

2023-06-16 07:45 UTC, jmark commented on src/mesh/vtk_helper.jl
> +    num_verts_on_edge = order - 1
Done.

2023-06-16 07:45 UTC, jmark commented on src/mesh/vtk_helper.jl
> +    )
Done.

2023-06-16 07:47 UTC, jmark commented on src/mesh/vtk_helper.jl
> +    )
Done.

2023-06-16 10:45 UTC, jlchan approved these changes
Thanks!

2023-06-16 10:45 UTC, merged