Added Gmsh 4.1 file format parser
jlchan/StartUpDG.jl pull request #28
Opened 2022-07-25 21:40 UTC by masonamccallum

Created readGmsh2D_v4 function. I can now group elements into regions/physical groups in Gmsh and then maintain those groupings on import. This way Physical parameters can be added for processing. For example in the mesh below I wanted a parameter m to be different on either side of the middle interface. 

![image](https://user-images.githubusercontent.com/33843826/180878447-639f870d-7381-4827-a750-2cc730e879cc.png)

2022-07-25 23:07 UTC, jlchan commented
@masonamccallum thanks very much for adding this functionality! 

I'll have a more detailed review tonight, but would you mind adding a test of your new Gmsh reader to this PR?

2022-07-25 23:08 UTC, jlchan commented
If you'd like, a test using the mesh you constructed would be a cool setup.

2022-07-25 23:41 UTC, jlchan requested changes
Thanks for adding this functionality! 

Here are some suggestions - feel free to ignore or discard any of them. I mostly added spacing between commas (input/output arguments) and some formatting. 

Once we get this merged, I'll release an update. I'd eventually like to make it so that the version is just automatically detected in the future.

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +struct MeshOptions
Could you add a docstring describing what `MeshOptions` is used for and how it should be used?

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +function getNumElements(lines,Dim=2)
Would you mind switching this to snake case `get_num_elements`? I'm trying to slowly bring the package more in line with the Julia style guide https://docs.julialang.org/en/v1/manual/style-guide/...

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    temp_numBlocks,_,_,_ = split(lines[elem_start])
```suggestion
    temp_numBlocks, _ = split(lines[elem_start])
```
I think the trailing `_` just discards other output arguments.

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    numBlocks = parse(Int,temp_numBlocks)
```suggestion
    numBlocks = parse(Int, temp_numBlocks)
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +        num_elem_in_block = parse(Int,temp_num_elem_in_block)
```suggestion
        temp_blockDim, _, _, temp_num_elem_in_block = split(lines[block_data_line])
        blockDim = parse(Int,t emp_blockDim)
        num_elem_in_block = parse(Int, temp_num_elem_in_block)
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +function remapElementGrouping!(eg)
```suggestion
function remap_element_grouping!(eg)
```
see above note on the Julia style guide

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    @unpack grouping,remapGroupName = options;
```suggestion
    @unpack grouping, remapGroupName = options;
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    version,_,dataSize = split(lines[format_line])
```suggestion
    version, _, dataSize = split(lines[format_line])
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    gmsh_version = parse(Float64,version)
```suggestion
    gmsh_version = parse(Float64, version)
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +        numPoints,numCurves,numSurfaces = entities_block_data[1:3]
```suggestion
        numPoints, numCurves, numSurfaces = entities_block_data[1:3]
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    VX,VY,VZ = ntuple(x->zeros(Float64,Nv),3)
```suggestion
    temp_numBlocks, temp_Nv, _ = split(lines[node_start])
    numBlocks = parse(Int, temp_numBlocks)
    Nv = parse(Int, temp_Nv)
    VX, VY, VZ = ntuple(x->zeros(Float64, Nv), 3)
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +            vals = [parse(Float64,c) for c in split(lines[node_cords_line])]
```suggestion
        _, _, _, temp_numNodes = split(lines[block_line])
        numNodes = parse(Int, temp_numNodes)
        for block_node_idx in 1:numNodes
            node_num_line = block_line + block_node_idx 
            node_cords_line = node_num_line + numNodes 
            node_idx_global = parse(Int, lines[node_num_line])
            vals = [parse(Float64, c) for c in split(lines[node_cords_line])]
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    temp_numBlocks,_,_,_ = split(lines[elem_start])
```suggestion
    temp_numBlocks, _ = split(lines[elem_start])
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +        element_grouping = zeros(Int,numElements) #element physical group assignment
```suggestion
        element_grouping = zeros(Int, numElements) #element physical group assignment
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    EToV = zeros(Int64,numElements,3)
```suggestion
    EToV = zeros(Int64, numElements, 3)
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +        surface_tag = parse(Int,temp_tag)
```suggestion
        temp_elem_block_dim, temp_tag, _, temp_elemInBlock = split(lines[block_line_start])
        elem_block_dim = parse(Int, temp_elem_block_dim)
        numElemInBlock = parse(Int, temp_elemInBlock)
        surface_tag = parse(Int, temp_tag)
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +                EToV[elem_global_idx,:] .= [nodeA,nodeB,nodeC]
```suggestion
                EToV[elem_global_idx,:] .= [nodeA, nodeB, nodeC]
```

2022-07-25 23:41 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +    gmsh_version = parse(Float64,version)
```suggestion
    format_line = findline("\$MeshFormat", lines)+1
    version, _, dataSize = split(lines[format_line])
    gmsh_version = parse(Float64, version)
```

2022-07-26 17:17 UTC, jlchan commented
Feel free to ping me if you have any questions or would like me to take another look!

2022-07-26 21:02 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +        blockDim = parse(Int,t emp_blockDim)
```suggestion
        blockDim = parse(Int, temp_blockDim)
```

2022-07-26 21:35 UTC, jlchan commented on src/mesh/simple_meshes.jl
> +        blockDim = parse(Int,t emp_blockDim)
Fixing a bug I introduced

2022-07-26 22:36 UTC, masonamccallum commented
Okay great! Ive made a bunch of changes to clean things up. I should be able to commit those fixes and the new tests early tomorrow. Thanks for the feedback!

2022-07-28 02:33 UTC, jlchan commented
@masonamccallum it looks like the tests for Julia v1.6 are failing. Can you take a look at those? If you need I can also try to figure out what's going on.

2022-07-28 03:42 UTC, masonamccallum commented
Ahh I used a feature in the testing library that requires Julia 1.7.

2022-07-28 03:43 UTC, jlchan commented
It looks like the tests are passing now. If you're cool with this PR as is, I can merge it and release a new version after they've passed.

2022-07-28 04:15 UTC, masonamccallum commented
Yeah that would be great! I was planning on setting up a function read_gmsh_2d that would determine the file format. I wanted your option on what it should return. The following would be a straight forward implementation.

`(VY,VX),EToV = read_gmsh_2d(filename)`
 
I would however like to get other data from the .msh files beyond just VXY and EToV. The file format for Gmsh 4.1 however doesn't lend itself well to implementing a separate function for extracting additional data. I think it would be better implementation to return a named tuple (or custom type) with relevant gmsh data that can then be unpacked.

2022-07-28 14:16 UTC, jlchan commented
> Yeah that would be great! I was planning on setting up a function read_gmsh_2d that would determine the file format automatically. I wanted your option on what it should return. The following would be a straight forward implementation.
> 
> `(VY,VX),EToV = read_gmsh_2d(filename)`

Minor note - should it be `(VX, VY)` instead of `(VY, VX)`?
> 
> I would however like to get other data from the .msh files beyond just VXY and EToV. The file format for Gmsh 4.1 however doesn't lend itself well to implementing a separate function for extracting additional data. I think it would be better implementation to return a named tuple (or custom type) with relevant gmsh data that can then be unpacked.

This sounds great. I think you could simply have the additional data returned at the end - the output of `read_gmsh_2d` is a tuple, and if you have more output arguments than entries of this tuple, then it will just extract the first few.

2022-07-28 14:18 UTC, jlchan commented
Another alternative to unifying the output arguments would be to build a custom struct for GMSH outputs and customize `iterate`. This does have the advantage of allowing dispatch on the mesh if we wanted to do so in the future.

2022-07-28 14:31 UTC, jlchan commented
Is the new implementation something you'd want to include in this PR or a later one?

2022-07-28 17:06 UTC, masonamccallum commented
A later PR is fine. At the moment I think the functionality is well tested and working.

2022-07-28 17:10 UTC, jlchan commented
Great, then I'll go ahead and merge this. Can you make an issue describing the new implementation?

2022-07-28 17:10 UTC, merged

2022-07-28 17:11 UTC, masonamccallum commented
Of course. Im on it

2022-07-28 17:18 UTC, jlchan commented
Registration for new version 0.13.8 at https://github.com/JuliaRegistries/General/pull/65213

2022-07-28 17:36 UTC, jlchan commented
And new version - https://github.com/jlchan/StartUpDG.jl/releases/tag/v0.13.8. Thanks again for this feature, @masonamccallum!