Write vtk
jlchan/StartUpDG.jl pull request #81
Opened 2023-01-26 15:00 UTC by Davknapp

Use WriteVTK to write meshes. To be able to represent the polynomials on the elements we use the lagrangian elements of vtk. 

In a first step we compute the permutation between the order of nodes in StartUpDG and vtk. We can then write them using that permutation.

Extracare is taken for the position of the nodes, since vtk assumes equidistant nodes.

2023-01-26 15:12 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +function SUD_to_vtk_order(rd::RefElemData, dim)
We can avoid having to pass in `dim` and instead infer it from `rd` via

```julia
function SUD_to_vtk_order(rd::RefElemData{DIM}) where {DIM}
```
Then `DIM` can be used as a variable inside the function.

2023-01-26 15:13 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +function Meshdata_to_vtk(md::MeshData, rd::RefElemData, dim, data, dataname, filename, write_data = false, equi_dist_nodes = true)
See comment on inferring `dim` from `md` or `rd` below.

2023-01-26 15:14 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +    num_lagrange_points = size(perm)[1]
```suggestion
    num_lagrange_points = size(perm, 1)
```
Or if `perm` is a vector, just doing `length` is clearer.

2023-01-26 15:15 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +    num_elements = size(md.EToV)[1]
```suggestion
    num_elements = md.num_elements
```
I've overloaded the `num_elements` property. You can also do `(; num_elements) = md` to unpack the argument.

2023-01-26 15:16 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +    cells = [MeshCell(vtk_cell_type, perm.+((i-1)*num_lagrange_points)) for i in 1:num_elements]
```suggestion
    cells = [MeshCell(vtk_cell_type, perm .+ ((i-1) * num_lagrange_points)) for i in 1:num_elements]
```

2023-01-26 15:17 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +    interpolate = diagm(ones(Float64, 10))
```suggestion
    interpolate = I(10)
```
This would create an identity matrix of size 10, which I think you're doing here.

2023-01-26 15:19 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +    vtkfile = []
Is there any way to know the type of `vtkfile` ahead of time? Initializing `vtkfile = []` will make a container with type `Any`, which can be slow. If you put `vtkfile = *VtkFileType*[]` it should work while being slightly more efficient.

2023-01-26 15:19 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +given by from and to. dim is the dimension of from and to.
```suggestion
Compute the coordinates of n equally distributed points between the points
given by `from` and `to`. `dim` is the dimension of `from` and `to`. 
```

2023-01-26 15:21 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +end
I prefer minimizing the number of arguments to pass in. I don't think you need `dim` as an argument here, can't you set `dim = length(from)`? Maybe with an `@assert length(from) == length(to)`.

2023-01-26 15:22 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +points of a VTK_LAGRANGE_WEDGE
```suggestion
Compute the coordinates of a `VTK_LAGRANGE_TRIANGLE` of a triangle or order `order` 
defined by the coordinates of the vertices given in `corner_verts`. `dim` is the
dimension of the coordinates given. If `skip` is set to true, the coordinates
of the vertex- and edge-points aren't computed, which can be used to compute
points of a `VTK_LAGRANGE_WEDGE`
```

2023-01-26 15:24 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    edges = [(1,2), (2,3), (3,1)]
I think you can get this from `rd.fv` too.

2023-01-26 15:25 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    inc = [(e_x+e_y) (-2*e_x + e_y) (e_x - 2*e_y)]
```suggestion
    e_x = (corner_verts[:,2] .- corner_verts[:,1]) ./ order
    e_y = (corner_verts[:,3] .- corner_verts[:,1]) ./ order
    inc = [(e_x + e_y) (-2*e_x + e_y) (e_x - 2*e_y)]
```

2023-01-26 15:25 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    return match_coordinate_vectors(vtk_formatted, equi_dist_vertices)
```suggestion
    #nodes in vtk order
    vtk_nodes = vtk_order(rd.element_type, rd.N)
    vtk_formatted = Tuple(vtk_nodes[i,:] for i in 1:dim)
    
    #nodes in StartUpDG order
    interpolate = vandermonde(rd.element_type, rd.N, equi_nodes(rd.element_type, rd.N)...) / rd.VDM
    equi_dist_vertices = Tuple(interpolate * rd.rst[i] for i in 1:dim)

    #permutation
    return match_coordinate_vectors(vtk_formatted, equi_dist_vertices)
```

2023-01-26 15:28 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +    coords = [vec(interpolate * md.xyz[i]) for i in 1:dim]
You have a similar line of code below as `Tuple(interpolate*rd.rst[i] for i in 1:dim)`. These are both fine, but can we make them consistent? 

Also, I often use `map` to do this:
```julia
coords = map(x -> vec(interpolate * x), md.xyz)
```
It may be more efficient in some cases, but it also doesn't require `dim` explicitly and just applies the specified function `x -> vec(interpolate * x)` to all elements of `md.xyz`.

2023-01-26 15:29 UTC, jlchan requested changes
Thank you for the PR! I looked through briefly and added some initial comments. I'll try to do a more in-depth review soon.

2023-01-30 15:32 UTC, jlchan requested changes
This looks really good! I suggested a few last changes for consistency and clarity, but then it should be ready to merge.

Thank you for the contribution!

2023-01-30 15:32 UTC, jlchan commented on src/StartUpDG.jl
> +export make_periodic, match_coordinate_vectors, match_coordinate_vectors!
Do we need to export these? I thought we just used these internally?

2023-01-30 15:32 UTC, jlchan commented on src/StartUpDG.jl
> +export VertexMeshPlotter, MeshPlotter, Meshdata_to_vtk, type_to_vtk, triangle_vtk_order
Do we need to export `type_to_vtk` or `triangle_vtk_order`? It seems like these are just used internally.

2023-01-30 15:32 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +function Meshdata_to_vtk(md::MeshData, rd::RefElemData{DIM}, data, dataname, filename, write_data = false, equi_dist_nodes = true) where {DIM}
For consistency, can we change `Meshdata` to `MeshData`?

2023-01-30 15:32 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +equi_dist_nodes flag if points should be interpolated to equidstant nodes
Could you put the i/o arguments inside single quote marks, e.g., `md`?

2023-01-30 15:32 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +dim is the dimension of the mesh
Should probably remove this now.

2023-01-30 15:32 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +data holds an array of arryas with data
spelling of "arrays". Also, is there a requirement for the format of `data`? It looks like `data[i]` is supposed to be a matrix of size `num_nodes` by `num_elements` - is that accurate?

2023-01-30 15:32 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +write_data, flag if data should be written or not
To my understanding, `write_data=false` means that only the mesh will be saved as output. If that's so, it might be helpful to mention in the comment.

2023-01-30 15:32 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +Construct all node-points of a VTK_LAGRANGE_TRIANGLE of order order. The corner-nodes are
`VTK_LAGRANGE_TRIANGLE`, `order`

2023-01-30 15:32 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    tri_sud_vertices = [-1.0 1.0 -1.0; -1.0 -1.0 1.0]
Can we replace this with `permutedims(hcat(nodes(Tri(), 1)...))`? This way, if we change the node ordering this automatically adapts?

2023-01-31 03:32 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +data holds an array of arryas with data
```suggestion
`data` holds an array of arrays (of size `num_nodes` by `num_elements`) with plotting data
```

2023-01-31 03:33 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +dim is the dimension of the mesh
```suggestion
```

2023-01-31 03:34 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +dataname is an array of strings with name of the associated data
```suggestion
`dataname` is an array of strings with name of the associated data
```
Can we also create a default argument for `dataname`, maybe something like `dataname = string.(eachindex(data))`?

2023-01-31 03:35 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +rd holds the reference element data.
```suggestion
`md` holds a `MeshData` object
`rd` holds a reference element data/`RefElemData` object. 
```

2023-01-31 03:35 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +write_data, flag if data should be written or not
```suggestion
`write_data`, flag if data should be written or not (e.g., if data is not written, only the mesh will be saved as output)
```

2023-01-31 03:36 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +equi_dist_nodes flag if points should be interpolated to equidstant nodes
```suggestion
`equi_dist_nodes` flag if points should be interpolated to equidstant nodes
```

2023-01-31 03:36 UTC, jlchan commented on src/mesh/mesh_visualization.jl
> +function Meshdata_to_vtk(md::MeshData, rd::RefElemData{DIM}, data, dataname, filename, write_data = false, equi_dist_nodes = true) where {DIM}
```suggestion
function MeshData_to_vtk(md::MeshData, rd::RefElemData{DIM}, data, dataname, filename, write_data = false, equi_dist_nodes = true) where {DIM}
```

2023-01-31 03:36 UTC, jlchan commented on src/StartUpDG.jl
> +export VertexMeshPlotter, MeshPlotter, Meshdata_to_vtk, type_to_vtk, triangle_vtk_order
```suggestion
export VertexMeshPlotter, MeshPlotter, MeshData_to_vtk, type_to_vtk, triangle_vtk_order
```

2023-01-31 03:37 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    edges = [(1,2), (2,3), (3,1)]
```suggestion
    edges = rd.fv
```
I think you can get edges from `rd.fv` (`fv` = face vertices). Can you check if this works? If so, it would be good to match `rd.fv` in case we change the order.

2023-01-31 03:37 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +Construct all node-points of a VTK_LAGRANGE_TRIANGLE of order order. The corner-nodes are
```suggestion
Construct all node-points of a `VTK_LAGRANGE_TRIANGLE` of order `order`. The corner-nodes are
```

2023-01-31 03:38 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    tri_sud_vertices = [-1.0 1.0 -1.0; -1.0 -1.0 1.0]
```suggestion
    tri_sud_vertices = permutedims(hcat(nodes(Tri(), 1)...))
```
This way, if we change the node ordering, the VTK writer will automatically adapt to it. Can you check that this works?

2023-02-06 17:15 UTC, jlchan commented on src/StartUpDG.jl
> +export make_periodic, match_coordinate_vectors, match_coordinate_vectors!
Can these be removed?

2023-02-06 17:16 UTC, jlchan commented
@Davknapp looks good! Only one question - can we avoid exporting `match_coordinate_vectors` and `match_coordinate_vectors!`? Otherwise, ready to merge.

2023-02-07 15:54 UTC, jlchan approved these changes

2023-02-07 16:08 UTC, jlchan commented
@Davknapp ready to merge?

2023-02-07 16:27 UTC, Davknapp commented
> @Davknapp ready to merge?

Ready to merge!

2023-02-07 19:33 UTC, merged