Add quads to vtk writer
jlchan/StartUpDG.jl pull request #83
Opened 2023-02-07 16:28 UTC by Davknapp

Add Quads to the vtk-writer. Similar to the triangle-vtk-writer.

2023-02-07 19:36 UTC, jlchan commented
@Davknapp it looks like this has some conflicts, and seems to duplicate some of the changes made in #81 too. Is there any way to fix this? For example, could you branch off of `main` now that #81 is merged and cherry pick the new commits from this PR?

2023-02-08 08:05 UTC, Davknapp commented
> @Davknapp it looks like this has some conflicts, and seems to duplicate some of the changes made in #81 too. Is there any way to fix this? For example, could you branch off of `main` now that #81 is merged and cherry pick the new commits from this PR?

I merged the current main-branch into this branch. The branch is directly build on #81 therefore it should solve the issue.

2023-02-08 18:47 UTC, jlchan requested changes
This looks good! I only have a few questions about assumptions in node and face orderings.

2023-02-08 18:47 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +given by the reference-triangle used by StartUpDG
```suggestion
Construct all node-points of a VTK_LAGRANGE_QUAD of order `order`. The corner-nodes are
given by the reference quadrilateral used by StartUpDG
```

2023-02-08 18:47 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +            tmp = n_verts_between(num_verts_on_edge, corner_verts[:,frm], corner_verts[:,to])
```suggestion
            tmp = n_verts_between(num_verts_on_edge, corner_verts[:, frm], corner_verts[:, to])
```

2023-02-08 18:47 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    e_y = (corner_verts[:,4] .- corner_verts[:,1])./order
```suggestion
    e_x = (corner_verts[:, 2] .- corner_verts[:, 1]) ./ order
    e_y = (corner_verts[:, 4] .- corner_verts[:, 1]) ./ order
```

2023-02-08 18:47 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    pos_y = copy(corner_verts[:,1])
```suggestion
    pos_y = copy(corner_verts[:, 1])
```

2023-02-08 18:47 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    quad_sud_vertices = [-1.0 1.0 1.0 -1.0; -1.0 -1.0 1.0 1.0]
The corner nodes are a little different from the default ordering - for example, 
```julia
julia> quad_sud_vertices = permutedims(hcat(nodes(elem, 1)...))
2×4 Matrix{Float64}:
 -1.0   1.0  -1.0  1.0
 -1.0  -1.0   1.0  1.0
```
which doesn't match `quad_sud_vertices`. Does that matter?

2023-02-08 18:47 UTC, jlchan commented on test/write_vtk_tests.jl
> +            interpolate = vandermonde(rd.element_type, rd.N, equi_nodes(rd.element_type, rd.N)...) /rd.VDM
```suggestion
            interpolate = vandermonde(rd.element_type, rd.N, equi_nodes(rd.element_type, rd.N)...) / rd.VDM
```

2023-02-08 18:47 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    edges = [(1,2), (2,3), (4,3), (1,4)]
This ordering is different from `StartUpDG.face_vertices(Quad())`. Does that matter? Is this just the ordering VTK uses?

2023-02-09 09:24 UTC, Davknapp commented on src/mesh/vtk_helper.jl
> +    edges = [(1,2), (2,3), (4,3), (1,4)]
This is the vtk-ordering

2023-02-09 09:25 UTC, Davknapp commented on src/mesh/vtk_helper.jl
> +    quad_sud_vertices = [-1.0 1.0 1.0 -1.0; -1.0 -1.0 1.0 1.0]
I think that my choice of variable-name and documentation wasn't perfect in this case. I updated it in the recent push and hope that it is better and more self-explainable now.

2023-02-09 15:32 UTC, jlchan commented on test/write_vtk_tests.jl
> +        return [-1.0 1.0 1.0 -1.0; -1.0 -1.0 1.0 1.0]
```suggestion
# test expected output of `vtk_order`
function deg_one_order(elem)
    if elem == Tri()
        return permutedims(hcat(nodes(Tri(), 1)...))
    elseif elem == Quad()
        return [-1.0 1.0 1.0 -1.0; -1.0 -1.0 1.0 1.0]
```

2023-02-09 15:32 UTC, jlchan commented on test/write_vtk_tests.jl
> +    end
```suggestion
# test expected output of `vtk_order`
function deg_zero_order(elem)
    #If the order of the tri-vertices changes in StartUpDG update this line.
    if elem == Tri()
        return [-1.0; -1.0]
    elseif elem == Quad()
        return [-1.0 1.0 1.0 -1.0; -1.0 -1.0 1.0 1.0]
    end
```

2023-02-09 15:34 UTC, jlchan approved these changes
LGTM! @Davknapp I'll merge it in about 30 minutes unless you say otherwise

I'll also release a new version since this should cover 2D VTK visualization.

2023-02-09 16:03 UTC, merged