Add wedge to vtk writer
jlchan/StartUpDG.jl pull request #88
Opened 2023-02-16 13:34 UTC by Davknapp

Added a vtk_writer for wedges. 

Had to change a line in the vtk-writer for quads, because the dimensions did not match of the quad-coords did not match the dimension of triangles and prisms/wedges.

2023-02-16 14:31 UTC, jlchan requested changes
Looks good! Only a few minor formatting suggestions and then we can merge it.

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    permutation = sortperm([corner_verts[:,i] for i in 1:size(corner_verts)[2]])
```suggestion
    permutation = sortperm([corner_verts[:, i] for i in 1:size(corner_verts, 2)])
```
Can you also add a comment on what this function does?

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +points of a VTK_LAGRANGE_WEDGE
```suggestion
Compute the coordinates of a `VTK_LAGRANGE_wedge` of a wedge of order `order` 
defined by the coordinates of the vertices given in `corner_verts`. `dim` is the
dimension of the coordinates given. If `skip` is set to `true`, the coordinates
of the vertex- and edge-points aren't computed, which can be used to compute
points of a `VTK_LAGRANGE_WEDGE`
```
The last part "which can be used to compute points of a `VTK_LAGRANGE_WEDGE`" is a little unclear. When would you want to set `skip=true`?

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +        tri_nodes = Matrix{Float64}(undef,dim,0)
```suggestion
        tri_nodes = Matrix{Float64}(undef, dim, 0)
```

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +            tri_nodes = hcat(tri_nodes,corner_verts[:,j])
```suggestion
            tri_nodes = hcat(tri_nodes, corner_verts[:, j])
```

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +            for i in range(1,size(face_coords)[2])
```suggestion
            for i in range(1,size(face_coords, 2))
```

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +            quad_nodes = hcat(quad_nodes, corner_verts[:,j])
```suggestion
        quad_nodes = Matrix{Float64}(undef, dim, 0)
        for j in indices
            quad_nodes = hcat(quad_nodes, corner_verts[:, j])
```

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +    for i in range(1,num_verts_on_edge)
```suggestion
    for i in range(1, num_verts_on_edge)
```

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +            for k in range(1,size(face_coords)[2])
```suggestion
            for k in 1:size(face_coords, 2)
```
For consistency (unless there's a reason you need `range`?)

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +Construct all node-points of a VTK_LAGRANGE_TRIANGLE of order order. The corner-nodes are
```suggestion
Construct all node-points of a VTK_LAGRANGE_QUAD of order `order`. The corner-nodes are
```

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +given by the reference-triangle used by StartUpDG
```suggestion
given by the reference-quadrilateral used by StartUpDG
```

2023-02-16 14:31 UTC, jlchan commented on src/mesh/vtk_helper.jl
> +given by the reference-triangle used by StartUpDG
```suggestion
Construct all node-points of a VTK_LAGRANGE_WEDGE of order `order`. The corner-nodes are
given by the reference wedge used by StartUpDG
```

2023-02-17 08:35 UTC, Davknapp commented on src/mesh/vtk_helper.jl
> +points of a VTK_LAGRANGE_WEDGE
For wedges never, I removed this part from the documentation

2023-02-17 14:19 UTC, jlchan approved these changes
LGTM - thanks!

2023-02-17 14:19 UTC, merged